# Site settings
title: YMC - Web Developer
description: "YMC 기술블로그"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://ymc-crow.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: YMC-양민철
user_title: YMC-양민철
email: ymch65@gmail.com
twitter_username: 
github_username:  ymc-crow
gplus_username:  
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: 
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: series
      url: /series
      key_trigger: 2
    - title: about me
      url: /about
      key_trigger: 3
    - title: every post
      url: /posts
      key_trigger: 4
  section_2:
    - title: JavaScript
      url: /javaScript
      key_trigger: js  
    - title: python
      url: /python
      key_trigger: py  

# projects in header index
projects:
  - name: jekyll로 기술블로그 만들기
    url: hhttps://github.com/ymc-crow/ymc-crow.github.io


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
